# This workflow will build the project and run unit tests 
name: Espm CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        maven: [ 3.8.5 ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'zulu'
    - name: Build with Maven
      run: mvn clean install
    - name: Deploy local
      run: |
          cd /customer-service
          mvn spring-boot:run
          cd ../product-service
          mvn spring-boot:run
          cd ../worker
          mvn spring-boot:run
          cd ../sale-service
          mvn spring-boot:run
          mvn clean install -pl gateway
    - name: Smoketest
      run: |
         npm install -g newman
         newman run /documentation/postman-collections/ESPM-LOCAL.postman_collection.json
          


          
      
